# Site Settings
locale          : "en-US"
title           : "TERA Proxy"
title_separator : "-"
name            : "Meishu"
description     : "Simple, easy, modular event handling through a TERA proxy server."
url             : "https://meishuu.github.io"
baseurl         : "/tera-proxy-test-pages" # TODO
repository      : "meishuu/tera-proxy"
teaser          : # path of fallback teaser image, e.g. "/assets/images/500x300.png"

# Social Sharing
og_image        : "/assets/images/site-icon.png"

# Site Author
author:
  name          : "Meishu"
  avatar        : "https://avatars.githubusercontent.com/meishuu"
  bio           : "Sleepy bun. Mystic main."
  location      : "Celestial Hills (NA)"
  email         :
  uri           :
  github        : "meishuu"
  tumblr        : "komyou"
  youtube       : "https://www.youtube.com/channel/UCvwqAzRW84t0wy_ubsAKbFA"

# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Gemfile
  - LICENSE

# Sass/SCSS
sass:
  style: compressed

# Outputting
timezone: America/Los_Angeles

# Plugins
gems: &gems
  - jekyll-avatar
  - jekyll-feed
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-sitemap

# mimic GitHub Pages with --safe
whitelist: *gems

# Collections
collections:
  changes:
    output: true

# Defaults
defaults:
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
  # _changes
  - scope:
      path: ""
      type: changes
    values:
      layout: version
      sidebar:
        nav: "changes"
